# Generated by Django 3.1.6 on 2021-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('text_prich', models.CharField(max_length=255, verbose_name='Причина выезда')),
                ('time_exit', models.CharField(max_length=25, verbose_name='Отметка об убытии')),
                ('time_enter', models.CharField(max_length=25, verbose_name='Отметка о прибытии')),
            ],
        ),
    ]
