# Generated by Django 3.1.6 on 2021-03-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210303_1319'),
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('name_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.name_job')),
            ],
        ),
    ]
