# Generated by Django 3.1.6 on 2021-03-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210303_1319'),
        ('jurnal', '0002_mainuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainUser',
            new_name='MainUsers',
        ),
        migrations.RenameField(
            model_name='mainusers',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='mainusers',
            old_name='username',
            new_name='username1',
        ),
    ]
