# Generated by Django 3.1.6 on 2021-03-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210310_1251'),
        ('jurnal', '0005_jurnal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='name_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.name_job'),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='date',
            field=models.DateField(),
        ),
    ]
