# Generated by Django 3.1.6 on 2021-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0006_auto_20210310_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnal',
            options={'verbose_name': 'Журнал выездов (не лезьте)', 'verbose_name_plural': 'Журнал выездов (не лезьте)'},
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='text_prich',
            field=models.CharField(max_length=255, verbose_name='Причина'),
        ),
    ]
