# Generated by Django 3.1.6 on 2021-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NpaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('pdf', models.FileField(upload_to='', verbose_name='PDF')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
