# Generated by Django 3.1.6 on 2021-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npalist',
            name='pdf',
            field=models.FilePathField(blank=True, null=True, verbose_name='PDF'),
        ),
    ]
