# Generated by Django 3.1.6 on 2021-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npa', '0002_auto_20210311_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npalist',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file', verbose_name='PDF'),
        ),
    ]
