# Generated by Django 3.1.6 on 2021-03-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npa', '0003_auto_20210311_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npalist',
            old_name='pdf',
            new_name='pdff',
        ),
    ]
