# Generated by Django 3.1.6 on 2021-03-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npa', '0007_auto_20210327_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npadoc',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npa_category', to='npa.npacategory', verbose_name='Категория'),
        ),
    ]
