# Generated by Django 3.1.6 on 2021-04-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npa', '0008_auto_20210327_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npacategory',
            options={'verbose_name': 'Категории НПА', 'verbose_name_plural': 'Категории НПА'},
        ),
        migrations.AlterModelOptions(
            name='npadoc',
            options={'verbose_name': 'Добавление НПА', 'verbose_name_plural': 'Добавление НПА'},
        ),
    ]
