# Generated by Django 3.1.6 on 2021-03-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gor_atc',
            field=models.CharField(max_length=255, verbose_name='Гор.АТС: '),
        ),
        migrations.CreateModel(
            name='MainPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО: ')),
                ('vnut_atc', models.IntegerField(verbose_name='Внут.АТС: ')),
                ('phone', models.CharField(max_length=255, verbose_name='Тел: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('name_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.name_job')),
            ],
        ),
    ]
