# Generated by Django 3.1.6 on 2021-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210302_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainperson',
            name='image',
            field=models.ImageField(null=True, upload_to='image_file', verbose_name='Фото: '),
        ),
    ]
