# Generated by Django 3.1.6 on 2021-03-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainperson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='index',
            field=models.IntegerField(null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='mainperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='mainperson',
            name='image',
            field=models.ImageField(null=True, upload_to='image_file', verbose_name='Фото '),
        ),
        migrations.AlterField(
            model_name='mainperson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО '),
        ),
        migrations.AlterField(
            model_name='mainperson',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Тел '),
        ),
        migrations.AlterField(
            model_name='mainperson',
            name='vnut_atc',
            field=models.IntegerField(verbose_name='Внут.АТС '),
        ),
        migrations.AlterField(
            model_name='name_job',
            name='name_job',
            field=models.CharField(max_length=255, verbose_name='Название структур '),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='person',
            name='gor_atc',
            field=models.CharField(max_length=255, verbose_name='Гор.АТС '),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='image_file', verbose_name='Фото '),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Должность '),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО '),
        ),
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.IntegerField(verbose_name='Кабинет '),
        ),
        migrations.AlterField(
            model_name='person',
            name='vnut_atc',
            field=models.IntegerField(verbose_name='Внут.АТС '),
        ),
    ]
