# Generated by Django 3.1.6 on 2021-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210310_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.CharField(max_length=10, verbose_name='Кабинет '),
        ),
    ]
