# Generated by Django 3.1.6 on 2021-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210313_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='person',
            name='vnut_atc',
            field=models.CharField(max_length=50, verbose_name='Внут.АТС'),
        ),
    ]
