# Generated by Django 3.1.6 on 2021-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210313_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpersonuser',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Кабинет '),
        ),
    ]
