# Generated by Django 3.1.6 on 2021-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mainpersonuser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpersonuser',
            name='job',
            field=models.CharField(blank=True, default='Начальник', max_length=100, null=True),
        ),
    ]
