# Generated by Django 3.1.6 on 2021-03-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210316_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name_otdel',
        ),
    ]
