# Generated by Django 3.1.6 on 2021-03-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_person_name_otdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_otdel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.name_otdel'),
        ),
    ]
