# Generated by Django 3.1.6 on 2021-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210316_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpersonuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_file', verbose_name='Фото '),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_file', verbose_name='Фото '),
        ),
    ]
