# Generated by Django 3.1.6 on 2021-03-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210318_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_otdel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_otdel', to='main.name_otdel'),
        ),
    ]
