# Generated by Django 3.1.6 on 2021-04-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210323_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpersonuser',
            name='name_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_job', to='main.name_job'),
        ),
    ]
