# Generated by Django 3.1.6 on 2021-04-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210406_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_otdel',
            name='name_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_job_otdel', to='main.name_job', verbose_name='Название структур'),
        ),
    ]
