# Generated by Django 3.1.6 on 2021-04-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210406_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpersonuser',
            options={'verbose_name': 'Добавление начальников', 'verbose_name_plural': 'Добавление начальников'},
        ),
        migrations.AlterModelOptions(
            name='name_job',
            options={'verbose_name': 'Добавление управлений', 'verbose_name_plural': 'Добавление управлений'},
        ),
        migrations.AlterModelOptions(
            name='name_otdel',
            options={'verbose_name': 'Добавление отделов', 'verbose_name_plural': 'Добавление отделов'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Добавление сотрудников', 'verbose_name_plural': 'Добавление сотрудников'},
        ),
    ]
