# Generated by Django 3.1.6 on 2021-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profcom',
            name='image',
        ),
        migrations.AddField(
            model_name='profcom',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profcom',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='profcom_file', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profcom',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
    ]
