# Generated by Django 3.1.6 on 2021-03-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0002_auto_20210325_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profcom',
            old_name='data',
            new_name='date',
        ),
    ]
