# Generated by Django 3.1.6 on 2021-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0004_profcomopros'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcom',
            name='full_text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
