# Generated by Django 3.1.6 on 2021-04-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0006_auto_20210406_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profopros',
            name='mac',
        ),
        migrations.CreateModel(
            name='Golos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.CharField(max_length=10, verbose_name='Голосы')),
                ('mac', models.CharField(max_length=30, verbose_name='Мак адрес')),
                ('opros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profcom.profopros', verbose_name='Опрос')),
            ],
        ),
    ]
