# Generated by Django 3.1.6 on 2021-04-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0007_auto_20210406_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListReclama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Называние')),
                ('url', models.CharField(max_length=250, verbose_name='Путь')),
            ],
        ),
        migrations.CreateModel(
            name='Reclama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='reclama_file', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profcom.listreclama')),
            ],
        ),
    ]
