# Generated by Django 3.1.6 on 2021-04-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profcom', '0008_listreclama_reclama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golos',
            options={'verbose_name': 'Результаты годосований', 'verbose_name_plural': 'Результаты голосований'},
        ),
        migrations.AlterModelOptions(
            name='listreclama',
            options={'verbose_name': 'Анонсы(не лезьте)', 'verbose_name_plural': 'Анонсы(не лезьте)'},
        ),
        migrations.AlterModelOptions(
            name='profcom',
            options={'verbose_name': 'Добавление мероприятий', 'verbose_name_plural': 'Добавление мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='profopros',
            options={'verbose_name': 'Добавления опросника', 'verbose_name_plural': 'Добавления опросника'},
        ),
        migrations.AlterModelOptions(
            name='reclama',
            options={'verbose_name': 'Добавление обьявлений', 'verbose_name_plural': 'Добавление обьявлений'},
        ),
    ]
